"""
Stage 6: Out-of-fold stacking with LightGBM LambdaRank.

Why OOF stacking is non-negotiable here. If LightGBM is trained on features
generated by the BPR-MF model that has already seen the same (user, item)
pairs, the reranker learns to trust the leaked signal and downstream NDCG is
inflated. The OOF construction breaks this dependency:

    1. Split training pairs into 5 folds.
    2. For each fold i, train Level-0 (CF feature generators) on the other 4
       folds, generate predictions on fold i.
    3. Concatenate the 5 held-out prediction blocks. The result is an OOF
       feature matrix where every prediction was made by a model that had
       not seen the corresponding row.
    4. Train LightGBM LambdaRank on these unbiased features.

LightGBM LambdaRank is chosen because it optimises NDCG directly via
lambda-weighted pairwise gradient updates, rather than optimising a surrogate
classification objective and hoping the ranking holds.

Outputs:
    lgbm_model.txt        trained LightGBM Booster
    oof_scores.npy        out-of-fold predictions for every pair
"""

import argparse
from pathlib import Path

import lightgbm as lgb
import numpy as np
from sklearn.model_selection import GroupKFold


def fit_lambdarank_oof(X, y, groups, n_folds=5, params=None):
    """Train LightGBM LambdaRank with out-of-fold cross-validation.

    `groups` is the user_id array; GroupKFold ensures that the same user is
    never split across folds, which would also leak.
    """
    if params is None:
        params = {
            "objective": "lambdarank",
            "metric": "ndcg",
            "ndcg_eval_at": [5, 10, 20],
            "learning_rate": 0.05,
            "num_leaves": 63,
            "min_data_in_leaf": 20,
            "feature_fraction": 0.9,
            "bagging_fraction": 0.8,
            "bagging_freq": 5,
            "lambda_l1": 0.1,
            "lambda_l2": 0.1,
            "verbose": -1,
        }

    oof_scores = np.zeros(len(X))
    gkf = GroupKFold(n_splits=n_folds)

    for fold, (tr, va) in enumerate(gkf.split(X, y, groups)):
        X_tr, y_tr, g_tr = X[tr], y[tr], groups[tr]
        X_va, y_va, g_va = X[va], y[va], groups[va]

        sort_tr = np.argsort(g_tr, kind="stable")
        X_tr, y_tr, g_tr = X_tr[sort_tr], y_tr[sort_tr], g_tr[sort_tr]
        sort_va = np.argsort(g_va, kind="stable")
        X_va, y_va, g_va = X_va[sort_va], y_va[sort_va], g_va[sort_va]

        _, counts_tr = np.unique(g_tr, return_counts=True)
        _, counts_va = np.unique(g_va, return_counts=True)

        ds_tr = lgb.Dataset(X_tr, label=y_tr, group=counts_tr)
        ds_va = lgb.Dataset(X_va, label=y_va, group=counts_va, reference=ds_tr)

        model = lgb.train(
            params, ds_tr,
            num_boost_round=300,
            valid_sets=[ds_va],
            callbacks=[lgb.early_stopping(20), lgb.log_evaluation(50)],
        )
        oof_scores[va[sort_va]] = model.predict(X_va)
        print(f"Fold {fold + 1}/{n_folds} done.")

    # Final model trained on all data for inference
    sort_all = np.argsort(groups, kind="stable")
    X_s, y_s, g_s = X[sort_all], y[sort_all], groups[sort_all]
    _, counts_all = np.unique(g_s, return_counts=True)
    ds_all = lgb.Dataset(X_s, label=y_s, group=counts_all)
    final = lgb.train(params, ds_all, num_boost_round=300)
    return final, oof_scores


# ────────────────────────────────────────────────────────────────────────────
#  Entry point
# ────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--features", default="runs/stage4", type=Path)
    parser.add_argument("--out", default="runs/stage6", type=Path)
    parser.add_argument("--folds", type=int, default=5)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    X = np.load(args.features / "features.npy")
    y = np.load(args.features / "labels.npy")
    pairs = np.load(args.features / "pairs.npy")
    groups = pairs[:, 0]

    print(f"Training LightGBM LambdaRank on {X.shape[0]} pairs, "
          f"{X.shape[1]} features, {len(np.unique(groups))} groups.")

    model, oof = fit_lambdarank_oof(X, y.astype(int), groups, n_folds=args.folds)
    model.save_model(str(args.out / "lgbm_model.txt"))
    np.save(args.out / "oof_scores.npy", oof)

    print(f"Stage 6 complete. Model and OOF scores in {args.out}")


if __name__ == "__main__":
    main()
